Cria tutorial de postagem por md
mobilizaFT/site-mobiliza pull request #44
Opened 2020-05-10 01:17 UTC by YuiMatsunaga

2020-05-11 20:44 UTC, alexandrebarbaruiva requested changes
Coloca o arquivo na raiz do projeto e muda o nome pra `CONTRIBUTING.md`

2020-05-12 14:55 UTC, cap-nascimento reviewed
No exemplo de novo vídeo do FT Ensina, o espaço para o h4 é o assunto da live (ou videoaula). Nesse exemplo está vazio porque não foi especificado o assunto pra esse video.

Seria assim o modelo:
# Nome do curso
## (titulo do video)
#### (assunto do video)
###### (link do video)

2020-05-13 01:32 UTC, cap-nascimento approved these changes

2020-05-13 19:12 UTC, YuiMatsunaga commented
@alexandrebarbaruiva aprovado?

2020-05-14 12:29 UTC, alexandrebarbaruiva approved these changes

2020-05-14 12:29 UTC, merged